name: Build .NET

on:
  push:
    branches: [ develop, main ]
  pull_request:
    branches: [ develop, main ]

defaults:
  run:
    working-directory: ./

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Setup .NET 6.0
        uses: actions/setup-dotnet@607fce577a46308457984d59e4954e075820f10a
        with:
          dotnet-version: 6.0.414
      - name: Install solution dependencies
        run: dotnet restore
      - name: Build
        run: dotnet build --configuration Release --no-restore
      - name: Test
        env:
          AWS_DEFAULT_REGION: us-west-2
          AWS_REGION: us-west-2
        run: dotnet test